set up confirmation page for new custos/oidc users
galaxyproject/galaxy pull request #10198
Opened 2020-09-08 15:46 UTC by juleengraham

2020-11-18 14:48 UTC, afgane requested changes
This lgtm, barring the issues with failing tests.

2020-11-18 14:48 UTC, afgane commented on client/src/components/login/Confirmation.vue
> +                                and password to connect this account via <strong>User Preferences</strong>.
```suggestion
                                and password to connect this account via <strong>User Preferences</strong>. <a href="https://galaxyproject.org/authnz/use/oidc/idps/custos/#link-an-existing-galaxy-account" target="_blank">See here</a> how.
```

2020-11-18 14:48 UTC, afgane commented on client/src/components/login/Confirmation.vue
> +                                to termination and data deletion. Connect existing account now to avoid possible loss of data.
```suggestion
                                to termination and data deletion on public Galaxy servers. Connect existing account now to continue to use your existing data and avoid possible loss of data.
```

2020-11-18 14:48 UTC, afgane commented on client/src/components/login/Confirmation.vue
> +                                    I have read and accept these terms.
```suggestion
                                    I have read and accept these terms to create a new Galaxy account.
```

2020-12-04 17:11 UTC, afgane approved these changes

2020-12-17 03:58 UTC, dannon commented
It looks like the new `create_user` bits here are duplication and need to be refactored, and I'm not seeing exactly where some of this code is hit anymore, but I know we want to go ahead and get this in and work with it.  We can refine it moving forward.

2020-12-17 04:02 UTC, merged