Git rid of JQuery from ToolHelp.vue
galaxyproject/galaxy pull request #14652
Opened 2022-09-19 12:51 UTC by MOHITRAJANI

Instead of using the function formattedComponent which in turn used Jquery selector to directly using the content that comes from props which is already having the HTML that we need to render in String format. Related to task #11939

(If fixing a bug, please add any relevant error or traceback)
(For UI components, it is recommended to include screenshots or screencasts)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

2022-09-19 13:26 UTC, dannon requested changes

2022-09-19 13:26 UTC, dannon commented on client/src/components/Tool/ToolHelp.vue
> -            const $tmpl = $("<div/>").append(this.content);
It looks like this substantively changes the incoming content, to me, and that functionality would need to be updated?

i.e. -- it makes all of the anchors target a new window, and it rewrites static references in the tool help.

2022-09-20 12:19 UTC, bgruening commented on client/src/components/Tool/ToolHelp.vue
> -            const $tmpl = $("<div/>").append(this.content);
And this PR turned green, and it should probably not :)
Please add some tests to make sure that the result is really the same before and after your modifications.

2022-10-13 20:05 UTC, bgruening commented
@MOHITRAJANI this needs a rebase and test.

2025-12-04 09:04 UTC, guerler commented
jQuery was removed in: 7391682.

2025-12-04 09:04 UTC, closed without merging