Workflow Enhancement: Exposing Workflow Version as Workflow Checkpoint
galaxyproject/galaxy pull request #16760
Opened 2023-09-28 16:50 UTC by assuntad23

Part of #16556 
Exposing the workflow version as workflow checkpoint on report. See comments in #16682 for reasoning. 

## How to test the changes?
(Select all options that apply)
- [X] Instructions for manual testing are as follows:
  1. Create a Workflow Report
  2. Note how Workflow Checkpoint is below the Title
  3. Note: if you do not see the Checkpoint, that is because it is waiting on the store to provide it, refreshing may work.  But I have it rendering conditionally, so if it doesn't return from the store in time, nothing is printed there instead. 

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

2023-09-29 10:25 UTC, nsoranzo commented
@davelopez suggested to call them "revisions" instead of checkpoints, as we do in pages and toolshed, was that ruled out?

2023-10-30 12:01 UTC, ElectronicBlueberry commented on client/src/components/Markdown/Markdown.vue
> +                    </h3>
```suggestion
                    <h2 v-if="workflowVersions" class="text-break align-middle">
                        Workflow Checkpoint: {{ workflowVersions.version }}
                    </h2>
```

[See here for more details](https://www.w3.org/WAI/tutorials/page-structure/headings/)

2023-10-30 12:01 UTC, ElectronicBlueberry commented on client/src/components/Markdown/Markdown.vue
> +        this.getWFversion();
```suggestion
        this.fetchWorkflowForInstanceId(this.workflowID);
```

2023-11-07 14:31 UTC, dannon requested changes
This looks like it likely breaks basic pages?  They won't have a workflow version or any of this stuff.

2023-11-07 15:24 UTC, dannon approved these changes

2023-11-07 15:24 UTC, merged