Jmol visualiser
galaxyproject/galaxy pull request #18540
Opened 2024-07-12 17:38 UTC by subindev-d

Added a visualizer for molecular structure files, using jsmol library.
Source of the contents in the static directory is from the original source of [Jmol](https://sourceforge.net/projects/jmol/), which is part of the pull request but included from the source as it it.
Screenshot of the visualizer:
![image](https://github.com/user-attachments/assets/b8c561e4-cf41-4cd3-a779-bdd91cbc84d7)

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  1. upload the follwing files and visualizeit [cif file](http://www.crystallography.net/cod/1000001.cif), [pdb file](https://files.rcsb.org/view/6r3q.pdb)
## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

2024-07-12 17:57 UTC, bgruening commented
Oh very cool! Thanks a lot @subindev-d!

Do you know [Mol* ](https://github.com/molstar/molstar), would that also be interesting for you use-case?

2024-07-15 09:38 UTC, subindev-d commented
> Oh very cool! Thanks a lot @subindev-d!
> 
> Do you know [Mol* ](https://github.com/molstar/molstar), would that also be interesting for you use-case?

This one looks interesting, I'll have a look thanks.

2024-10-07 07:11 UTC, guerler requested changes
Thank you for working on this. There is one issue with this PR. We recently moved away from committing visualization specific scripts directly into the repo. The Galaxy Visualization XMLs allow installing npm dependencies using the `<requirements>` tag.

`<requirements>
        <requirement type="npm" version="0.0.1" package="your_npm_package"/>
</requirements>`

Just make sure that the `npm run build` command produces a `static` or `dist/static` directory with your js-script files. By moving the js-script files out of the Galaxy repo, we ensure proper versioning of visualization plugins and keep the core repo size at bay. Examples for this approach are the `msa` and `ngl` viewers.

Please let me know if you have any questions or need further assistance.

2024-10-21 09:19 UTC, hechth commented
@subindev-d this looks very cool, which file types are you supporting?

Also, let me know if you are interested in Mol*.

2025-09-01 15:29 UTC, closed without merging

2025-09-01 15:29 UTC, subindev-d commented
As the visualizations in galaxy is moved to galaxy-visualizations repo this pull request is not relevant.