Refactor and use `ScrollList` component in more places
galaxyproject/galaxy pull request #19318
Opened 2024-12-12 11:33 UTC by mvdbeek

# Custom Tools Panel updates
The Custom Tools panel now uses `GCard` in the existing `ScrollList`. This allows for nicer action buttons and badges.

| Before | After |
| ---- | ---- |
| <img width="337" height="864" alt="firefox_VGv46860af" src="https://github.com/user-attachments/assets/c7c952f6-f269-4b45-8683-de82a2f38c19" /> | <img width="337" height="864" alt="AiDPsKKJ1L" src="https://github.com/user-attachments/assets/147fcda5-0358-4047-9622-b2460c487083" /> |

# HistoryScrollList updates
The `HistoryScrollList` component now uses `ScrollList` and `GCard`.

## Current History Selector

| Before | After |
| ---- | ---- |
| <img width="722" height="842" alt="firefox_xlPpzFX9n2" src="https://github.com/user-attachments/assets/69838e3e-a028-4123-a57b-d372dc353c59" /> | <img width="722" height="842" alt="H56w2jcrTl" src="https://github.com/user-attachments/assets/d46f13ae-c2d0-45be-9b25-5bead6c50878" /> |

## History Multiview Selector Modal

| Before | After |
| ---- | ---- |
| <img width="722" height="841" alt="GM6SNXLDA2" src="https://github.com/user-attachments/assets/c1a652dd-f4a5-48c3-8916-a29aeffebacd" /> | <img width="722" height="841" alt="4kgGDwdUhs" src="https://github.com/user-attachments/assets/75cb5821-4923-446f-a9dd-5f3a0ea16493" /> |

## History Multiview Selector Panel

| Before | After |
| ---- | ---- |
| <img width="334" height="863" alt="firefox_PqwcJxsp3v" src="https://github.com/user-attachments/assets/d75c550a-76a2-4cca-8402-db5ce5b187cb" /> | <img width="334" height="863" alt="pp5RdlV7e2" src="https://github.com/user-attachments/assets/dec85a39-f63a-468a-ab65-d31154c2cfec" /> |

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [x] This is a refactoring of components with existing test coverage.
- [ ] Instructions for manual testing are as follows:
  1. [add testing steps and prerequisites here if you didn't write automated tests covering all your changes]

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

2025-07-22 23:11 UTC, ahmedhamidawan commented
The failing seleniums like:
```
FAILED lib/galaxy_test/selenium/test_visualizations.py::TestVisualizations::test_charts_tabulator - 
selenium.common.exceptions.TimeoutException: Message: Timeout waiting on CSS selector [#center [data-plugin-name*="tabulator"]] to become visible.
```
are related. I decided to use the `ScrollList` in the `VisualizationPanel` as well for styling benefits. Will fix those!

2025-07-23 09:14 UTC, itisAliRH requested changes
Thank you @ahmedhamidawan for working on this. I added some comments for your review.

2025-07-23 09:14 UTC, itisAliRH commented on client/src/components/History/HistoryScrollList.vue
> +import type { CardAction, CardBadge } from "../Common/GCard.types";
```suggestion
import type { CardAction, CardBadge } from "@/components/Common/GCard.types";
```

2025-07-23 09:14 UTC, itisAliRH commented on client/src/components/History/HistoryScrollList.vue
> +import ScrollList from "../ScrollList/ScrollList.vue";
```suggestion
import GCard from "@/components/Common/GCard.vue";
import ScrollList from "@/components/ScrollList/ScrollList.vue";
```

2025-07-23 09:14 UTC, itisAliRH commented on client/src/components/History/HistoryScrollList.vue
> +            <!-- TODO: Long history names should be truncated, esp in multiview panel -->
We may need this in other places as well. I think we should create it in GCard and control it using a prop.

2025-07-23 09:14 UTC, itisAliRH commented on client/src/components/History/HistoryScrollList.vue
> +                </template>
`GCard` can do this part using its props. e.g. [WorkflowCard](https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/Workflow/List/WorkflowCard.vue#L128) has tags.

2025-07-23 09:14 UTC, itisAliRH commented on client/src/components/Panels/UserToolPanel.vue
> +import GCard from "../Common/GCard.vue";
```suggestion
import GButton from "@/components/BaseComponents/GButton.vue";
import GButtonGroup from "@/components/BaseComponents/GButtonGroup.vue";
import GCard from "@/components/Common/GCard.vue";
```

2025-07-23 09:14 UTC, itisAliRH commented on client/src/components/ScrollList/ScrollList.vue
> +import LoadingSpan from "../LoadingSpan.vue";
```suggestion
import GButton from "@/components/BaseComponents/GButton.vue";
import LoadingSpan from "@/components/LoadingSpan.vue";
```

2025-07-23 09:14 UTC, itisAliRH commented on client/src/components/Visualizations/VisualizationPanel.vue
> +import ScrollList from "../ScrollList/ScrollList.vue";
```suggestion
import ScrollList from "@/components/ScrollList/ScrollList.vue";
```

2025-07-23 14:42 UTC, ahmedhamidawan commented on client/src/components/History/HistoryScrollList.vue
> +                </template>
Ah! You're right, my bad, will use the props for tags.

2025-07-23 18:01 UTC, itisAliRH commented on client/src/components/History/HistoryScrollList.vue
> +                </template>
NP! It also works for description.

2025-07-23 21:42 UTC, ahmedhamidawan commented on client/src/components/History/HistoryScrollList.vue
> +            <!-- TODO: Long history names should be truncated, esp in multiview panel -->
This was tricky 😓 

Final result is, I've had to compromise with the only apparent styling bug i.e. a badly positioned tooltip:

<img width="367" height="364" alt="firefox_C5bNjUHLMV" src="https://github.com/user-attachments/assets/a099c36b-3beb-49fe-870d-df03d841acc7" />

### There's a comment that explains why I did this:
(I guess ~height setting~ ✖️  display setting* ✔️ )

https://github.com/galaxyproject/galaxy/blob/8901374d695336fa520fada762a312a758709ee6/client/src/components/Common/GCard.vue#L717-L727

Any tips or is this good as is? Feel free to push etc too!

2025-07-25 10:57 UTC, itisAliRH commented on client/src/components/History/HistoryScrollList.vue
> +            <!-- TODO: Long history names should be truncated, esp in multiview panel -->
@ahmedhamidawan I could fix the tooltip issue.

2025-07-25 14:14 UTC, itisAliRH approved these changes

2025-07-25 19:47 UTC, itisAliRH commented
Failing tests are irrelevant.

2025-07-28 13:22 UTC, merged