16.10 Configuration & Server Overhaul - Tool Shed and Reports
galaxyproject/galaxy pull request #2866
Opened 2016-08-26 20:27 UTC by jmchilton

- Follow up on broken #2837 with an at least less broken attempt bring startup scripts and config processing inline between Galaxy, Reports, and the Tool Shed.
- Define a schema format and tooling (derived from pywalify) to define web server and application option documentation and validation.
- Update Galaxy common startup functions to allow starting up uwsgi.
- Update Galaxy to allow YAML-based configuration files.
- Switch out of the box server for use by tool shed and reports to uwsgi.
- Add schema validation for uwsgi options (derived from uwsgi docs).
- Add validation/documentation schema for tool shed including
   - Utilities to convert of .ini configs to new YAML ones and switch paste to uwsgi.
   - Build a new yaml sample that targets uwsgi out of the box.
   - Utility to validate a tool shed configuration file in the new YAML format.
- Add validation/documentation schema for reports including
   - Utilities to convert of .ini configs to new YAML ones and switch paste to uwsgi.
   - Build a new yaml sample that targets uwsgi out of the box.
   - Utility to validate a reports configuration file in the new YAML format.
- Add reports documentation to the admin section and documentation of the configuration options derived from the schema.

There is no additional duplication between various items (before a .ini.sample had a default and description) now the schema defines these items and everything else (docs, validation, sample YAML) are derived from that. The new validation format should be more usable from within the actual applications themselves to replace existing type conversion and default handling logic - an exciting future direction for this work.

This is hopefully a test bed to bring these concepts quickly to Galaxy - I think all of the infrastructure needed to do this is now readily available after this PR.

2016-09-07 14:36 UTC, martenson commented
is this ready for review @jmchilton ?

2016-09-07 16:24 UTC, jmchilton commented
@martenson - Absolutely.

2016-09-14 19:05 UTC, martenson commented on scripts/config_manage.py
> +                message = "Additional sever section after [%s] encountered [%s], will be ignored."
s/sever/server

2016-09-14 19:05 UTC, martenson commented on Makefile
> +reports-config-convert: ## convert old style reports ini to yaml
When trying to convert my config using this I get the following output in the console but no new file is created and reports.ini remains the same.

```
$ make reports-config-convert
if [ -f .venv/bin/activate ]; then . .venv/bin/activate; fi; python scripts/config_manage.py convert reports
uwsgi:

  http: 127.0.0.1:9001

  threads: 10

  http-raw-body: True

  offload-threads: 8

reports:

  database_connection: postgres://<usr:pswd>@localhost:5432/galaxy-git
```

2016-09-14 19:05 UTC, martenson commented on Makefile
> +reports-config-convert: ## convert old style reports ini to yaml
This output above seems to be missing the `module: galaxy.webapps.reports.buildapp:uwsgi_app()` line which is in the yml.sample however even if I add it I am getting the following error when trying to use the yml config as reports.ini: 
```
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /Users/marten/devel/git/galaxy/config/reports.ini, line: 1
'uwsgi:\n'
```

When I take the whole new config (in yml) and paste it to the reports.yml.sample (removing the reports.ini completely) it also does not work. (With vanilla sample config run the app runs ok.)

2016-09-14 19:30 UTC, martenson commented on scripts/config_manage.py
> +        _warn("Path [%s] not a file, using sample.")
this does not seem to succeed for reports sample:
```
$ make reports-config-validate
if [ -f .venv/bin/activate ]; then . .venv/bin/activate; fi; python scripts/config_manage.py validate reports
WARNING: Path [%s] not a file, using sample.
Traceback (most recent call last):
  File "scripts/config_manage.py", line 473, in <module>
    main()
  File "scripts/config_manage.py", line 188, in main
    _validate(args, app_desc)
  File "scripts/config_manage.py", line 283, in _validate
    schema_files=[name],
TypeError: 'NoneType' object is not callable
make: *** [reports-config-validate] Error 1
```

2016-09-14 19:34 UTC, martenson commented on scripts/config_manage.py
> +    path = app_desc.destination
this does not seem to correctly read the app_desc since it does not find `config/reports.ini` when running `$ make reports-config-validate`

2016-09-14 19:38 UTC, martenson requested changes
This is feedback on the Reports webapp part only. I like the way this is heading; please see few problems I have encountered inline. 

General question: do you expect trouble converting deployers' old configurations into the yaml format? Do you expect to do this migration by default in some future release?
Thanks for working on this @jmchilton

2016-09-14 20:10 UTC, jmchilton commented
> Do you expect trouble converting deployers' old configurations into the yaml format?

I wouldn't expect it to be perfect, but I think we can do a good job.

> Do you expect to do this migration by default in some future release?

Definitely not.

2016-09-15 17:28 UTC, martenson commented
@jmchilton Do you want me to review the TS part at the moment or should I wait for the resolution of the reports feedback?

2016-09-15 17:44 UTC, jmchilton commented
@martenson As long as you have no ... ... big picture objections to anything I'll dig back in and keep working on this this afternoon and hopefully have an update. If you want to wait for that - it would seem totally fair. There is some pressure to get this done to increase the robustness of the GIEs.

2016-09-15 18:08 UTC, martenson commented
@jmchilton I will review again tomorrow then, focusing on the TS side.

2016-09-15 20:07 UTC, jmchilton commented on scripts/config_manage.py
> +    path = app_desc.destination
Validate currently only works on the YAML files, I'll see if I can make that more clear.

2016-09-15 20:21 UTC, martenson commented on scripts/config_manage.py
> +    path = app_desc.destination
It was a yaml file. Do you mean that it has to end `.yml`?

2016-09-16 13:44 UTC, jmchilton commented
@martenson I made some good progress addressing your issues yesterday but today I'm working on setting up unit tests for all of this - might be best to wait another day before reviewing again.

2016-09-16 14:24 UTC, martenson commented
🎷

2016-09-19 01:13 UTC, closed without merging

2016-09-19 01:13 UTC, jmchilton commented
Closing this until I can schedule some time with @natefoo to go over it.

2016-09-23 18:10 UTC, jmchilton commented
@natefoo gave me some advice on prefixing with uwsgi:

 - http://stackoverflow.com/questions/11292217/run-django-app-via-nginxuwsgi-in-a-subpath
 - http://uwsgi-docs.readthedocs.io/en/latest/Nginx.html#hosting-multiple-apps-in-the-same-process-aka-managing-script-name-and-path-info

2016-11-15 15:46 UTC, jmchilton commented
## Prefix with an nginx proxy 

Actually seems simpler than before. All needed in nginx.conf is:

```
    upstream shed_app {
        server 127.0.0.1:9009;
    }

   ...

   server {
        ...
        location /shed {
            uwsgi_pass shed_app;
            include uwsgi_params;
        }
        ...
   }
```

tool_shed.yml requires following fields:

```
uwsgi:
  socket: 127.0.0.1:9009
  mount: /shed=galaxy.webapps.tool_shed.buildapp:uwsgi_app()
  manage-script-name: true
```

# Prefix without nginx proxy:

```
uwsgi:
  http: 127.0.0.1:9009
  mount: /shed=galaxy.webapps.tool_shed.buildapp:uwsgi_app()
  manage-script-name: true
```

2016-11-15 16:10 UTC, martenson commented
@jmchilton do you want to re-open this and push for a release inclusion?

2016-11-15 16:14 UTC, jmchilton commented
@martenson Nope - no rush on my part. Happy with this being the "2017" way to deploy Galaxy :smile:.

2016-11-15 16:15 UTC, martenson commented
I thought 2017 is the year of `$ apt-get install galaxy` 😉

2016-11-15 16:17 UTC, jmchilton commented
It will be - I updated my comment with more precise language.

2016-11-15 16:19 UTC, martenson commented
@jmchilton updating comments to make me look silly!

2016-11-15 17:45 UTC, natefoo commented
:100:

2016-11-15 20:55 UTC, jmchilton commented
Proxy prefix handling now handled in https://github.com/jmchilton/galaxy/commit/a4132f054246fb7f192cfac9d3eddda7ff96dacd - linking the individual commit since it will likely be rebased into larger commit before next PR.