Fix whoosh indexing in 16.07.
galaxyproject/galaxy pull request #2949
Opened 2016-09-21 18:41 UTC by davebx

2016-09-21 18:44 UTC, martenson commented
👍

2016-09-23 14:21 UTC, nsoranzo commented on scripts/tool_shed/build_ts_whoosh_index.py
> +from galaxy.util import directory_hash_id
To make Travis happy, this should be merged in line 26:
```
from galaxy.util import directory_hash_id, pretty_print_time_interval
```

2016-09-23 14:21 UTC, nsoranzo requested changes

2016-09-23 16:56 UTC, nsoranzo approved these changes

2016-09-23 16:58 UTC, merged