[16.04] backport of model tool dependencies fix
galaxyproject/galaxy pull request #2959
Opened 2016-09-22 18:56 UTC by martenson

xref: https://github.com/galaxyproject/galaxy/pull/2950
ping @nsoranzo @davebx

2016-09-22 18:57 UTC, martenson commented on lib/galaxy/webapps/tool_shed/controllers/repository.py
>          repository = suc.get_repository_by_name_and_owner( trans.app, name, owner )
I had to change this to `suc.`

2016-09-22 19:07 UTC, nsoranzo commented on lib/galaxy/webapps/tool_shed/controllers/repository.py
>          repository = suc.get_repository_by_name_and_owner( trans.app, name, owner )
That was expected: https://github.com/galaxyproject/galaxy/pull/2950#discussion_r80083956

2016-09-22 19:08 UTC, martenson commented on lib/galaxy/webapps/tool_shed/controllers/repository.py
>          repository = suc.get_repository_by_name_and_owner( trans.app, name, owner )
@nsoranzo that's why I had no problems doing it :)

2016-09-22 19:15 UTC, nsoranzo commented on lib/galaxy/webapps/tool_shed/model/__init__.py
> +        changeset_revision = metadata_util.get_next_downloadable_changeset_revision( self, repo, changeset_revision )
Actually that's the one that should be changed: `s/metadata_util/suc/`

2016-09-22 19:15 UTC, nsoranzo requested changes

2016-09-22 19:46 UTC, martenson commented on lib/galaxy/webapps/tool_shed/model/__init__.py
> +        changeset_revision = metadata_util.get_next_downloadable_changeset_revision( self, repo, changeset_revision )
interesting, that one was not in conflict...

2016-09-22 19:50 UTC, nsoranzo commented on lib/galaxy/webapps/tool_shed/model/__init__.py
> +        changeset_revision = metadata_util.get_next_downloadable_changeset_revision( self, repo, changeset_revision )
Because these are new lines.

2016-09-22 20:01 UTC, martenson commented on lib/galaxy/webapps/tool_shed/model/__init__.py
> +        changeset_revision = metadata_util.get_next_downloadable_changeset_revision( self, repo, changeset_revision )
good catch

2016-09-22 20:02 UTC, martenson commented on lib/galaxy/webapps/tool_shed/controllers/repository.py
>          repository = suc.get_repository_by_name_and_owner( trans.app, name, owner )
heh, seems I had plenty of problems doing it :D

2016-09-22 20:16 UTC, nsoranzo commented
The TS test is still failing, but I think this should be fixed by updating the freebayes version in `test/shed_functional/functional/test_1400_review_migration_stages.py` . Testing it now.

2016-09-22 20:20 UTC, nsoranzo commented
Confirmed. @martenson, can you add the following to this PR ? I have to go home.
```
diff --git a/test/shed_functional/functional/test_1400_review_migration_stages.py b/test/shed_functional/functional/test_1400_review_migration_stages.py
index 8499b68..926f30a 100644
--- a/test/shed_functional/functional/test_1400_review_migration_stages.py
+++ b/test/shed_functional/functional/test_1400_review_migration_stages.py
@@ -29,7 +29,7 @@ class TestToolMigrationStages( ShedTwillTestCase ):
                                       'blast_datatypes', 'bwa_wrappers', 'picard', 'lastz',
                                       'lastz_paired_reads', 'bowtie_color_wrappers', 'bowtie_wrappers',
                                       'xy_plot', 'bam_to_sam' ]
-        migrated_tool_dependencies = [ 'emboss', '5.0.0', 'freebayes', '0.9.4_9696d0ce8a962f7bb61c4791be5ce44312b81cf8',
+        migrated_tool_dependencies = [ 'emboss', '5.0.0', 'freebayes', '0.9.4_a46483351fd0196637614121868fb5c386612b55',
                                        'samtools', '0.1.18', 'blast+', '2.2.26+', 'bwa', '0.5.9', 'picard', '1.56.0',
                                        'lastz', '1.02.00', 'bowtie', '0.12.7', 'FreeBayes requires g++', 'ncurses', 'zlib',
                                        'blast.ncbi.nlm.nih.gov', 'fastx_toolkit', '0.0.13', 'samtools', '0.1.16', 'cufflinks',
```

2016-09-22 21:49 UTC, martenson commented
thanks @nsoranzo - we discussed the need to do this with @davebx previously but then it vanished from our minds

2016-09-22 22:59 UTC, nsoranzo approved these changes

2016-09-23 13:30 UTC, merged

2016-09-23 16:56 UTC, nsoranzo commented
Forward merged.