Unite workflow execution api endpoints
galaxyproject/galaxy pull request #2969
Opened 2016-09-23 23:44 UTC by guerler

Resolves #2899, branched from #2935.

2016-09-28 14:45 UTC, jmchilton requested changes
I have a couple specific comments also - but at a high-level I was hoping you could throw a flag in there to indicate the response should contain multiple invocations. It seems a bit like magic that if only one invocation if produced a map is returned but if many are produced a list is returned. If the request contained `'multi_request': True` or `batch: True` and then returned a list I would be more comfortable. I'd even more prefer if the batching were done on the client of through the batching stuff Carl wrote - but I understand the pragmatic concerns here.

2016-09-28 16:49 UTC, guerler commented
Feel free to correct me but if I understand this right, this is already the case. A list of invocations is only returned if one of the parameters has specified `batch=true` otherwise a single map is returned.

2016-09-30 05:56 UTC, guerler commented
The request now always returns a list if `input_params` is specified, https://github.com/galaxyproject/galaxy/pull/2969/commits/1cb67308771edf40716ef5f30f4321051debc4bb#diff-2fca1f4002bba50737993fd85ce5800fR454.

2016-09-30 10:44 UTC, jmchilton commented
@guerler I'd really like to unify the ``input_params`` with the existing ``parameters`` approach. I don't want the batch mode options to be available in one and not the other - it also isn't very intuitive from the parameter name ``input_params`` that if it is specified you get a list back. I know it feels redundant in some ways, but I think it would be better if the UI explicitly asked for a list back (``enable_batch_processing: True`` or ``batch: True``). It would be easier for the endpoint consumer to understand and it would enable us to make more progress toward uniting ``input_params`` and ``parameters``.

2016-09-30 18:15 UTC, nsoranzo commented
It would be nice to test if this breaks BioBlend before merging.

2016-09-30 18:16 UTC, jmchilton reviewed
Sorry if I seem picky - I do appreciate this particular change - I think it is important improvement.

2016-09-30 18:43 UTC, jmchilton commented
@guerler - about this...
```
new_history.copy_tags_from( trans.user, trans.history )
```

is that intentional? That seems wrong - but was it copied from the old code in the UI controller or something?

2016-09-30 18:49 UTC, guerler commented
@jmchilton its not a big deal.

2016-09-30 18:52 UTC, jmchilton commented
@guerler 

```
                if len( param_keys ) > index:
                    ids = param_keys[ index ]
```

This should just be:

```
                if len( param_keys ) > 0:
                    ids = param_keys[ index ]
```

Or something like that right? param_keys is the hids of things being batched up right?

2016-09-30 19:12 UTC, jmchilton commented
I opened some PRs to merge approaches to history handling and make the return value of the run_request method more consistent. Let me know if either is objectionable. I haven't tested them extensively yet but I'd like to know if you are okay with general directions of the refactorings.

2016-09-30 19:14 UTC, guerler commented
The conditional double checks the result of the parameter expansion. We could remove it entirely, but I do not see any harm leaving it in. The conditional should never fail unless there is a bug in the parameter expansion procedure.

2016-09-30 19:19 UTC, jmchilton commented
@guerler I see - that makes sense now - I was mistaking this as the ``if nids == 0`` case - but  I see that is just taken care of but not doing anything in that nested conditional. I'd drop the new exception and place an assertion in there instead of a conditional - it feels like the most Pythonic thing to do.

2016-09-30 19:51 UTC, jmchilton commented
@nsoranzo - I'll definitely run the BioBlend tests and I'll PR enhancements coming out of this work -descriptions of the batch functionality and the flattened parameter style @guerler prefers here.

2016-10-01 01:18 UTC, jmchilton commented
@guerler - You can sort keys before iterating over them during expansion to make it deterministic right?

2016-10-01 01:24 UTC, jmchilton commented
@guerler I just noticed you are exposing unencoded IDs with the new run export. Can we fix that before the release? I feel strongly that we shouldn't be exposing unencoded IDs over the API - it has long been a design goal of the API I think. It should be possible to represent everything with ``order_index`` - to whatever extent we can use that the API is more usable and stable to client libraries and humans hacking around.

2016-10-01 03:17 UTC, jmchilton commented
https://github.com/guerler/galaxy/pull/13 I think includes a bunch of refactoring so that instead of branching based on approach in ``build_workflow_run_config`` at the very outer part of a huge function and doing very different things and handling different parameters - everything is handled in one big loop with more consistent parameter handling. The following parameters ``history``, ``history_id``, ``history_id``, ``inputs``, ``ds_map``, ``inputs_by``, ``legacy``,  and ``no_add_to_history`` are now handled consistently across approaches (UI, existing API) - before https://github.com/guerler/galaxy/pull/13 each of these parameters would only apply to one branch or the other of this code. In addition initial ``WorkflowRunConfig`` objects to be persisted are now only created in one place - one line of code - I think this is strong evidence that we now just have that one path through the code.

The thing that this part of the run UI continues to do which I think is unfortunate is write IDs to JSON blobs in ``WorkflowRequestStepState.state`` for input steps instead of properly using ``WorkflowRequestToInputDatasetAssociation`` or ``WorkflowRequestToInputDatasetCollectionAssociation`` model objects / tables which provide referential integrity and stronger typing since these uses the database more appropriately. I don't think that issue needs to hold this up though.

2016-10-01 03:35 UTC, jmchilton approved these changes

2016-10-02 13:29 UTC, jmchilton commented on lib/galaxy/managers/workflows.py
> +            step_model[ 'step_id' ] = trans.app.security.encode_id( step.id )
Do you have a reason not to just use the ``order_index`` for these? The other export endpoints do this and I think we should be consistent - I also think this makes the API more "usable". I can't think of a reason the GUI should need to know the step ID when the invocation API doesn't use it and the workflow editor doesn't use it - is there one?

2016-10-02 18:21 UTC, guerler commented on lib/galaxy/managers/workflows.py
> +            step_model[ 'step_id' ] = trans.app.security.encode_id( step.id )
Yeah whatever uniquely identifies the step would work. I used the id because its native to the WorkflowStepConnection model.

2016-10-03 16:05 UTC, guerler commented
@galaxybot test this

2016-10-03 19:57 UTC, guerler commented
@galaxybot test this

2016-10-04 02:34 UTC, jmchilton commented
You disappeared from IRC:

```
01:20 <jmchilton> I think you want to sort the keys - not the items 
01:21 <jmchilton> maybe it doesn't matter - but I don't know what sorting a tuple like 
                  that does 
01:22 <jmchilton> I mean - I guess it work on the first item... hmmm... 
01:25 <jmchilton> Okay - I guess the thing is that the invocations do get queued -  
                  there is no guarentee which will start adding to the history first 
01:25 <jmchilton> it is like submitting jobs in a given order and expecting them to  
                  run in the same order - Galaxy doesn't do that 
01:26 <jmchilton> I guess I don't consider that a problem - we could work on FIFO-ing  
                  the workflow scheduler though 
```

2016-10-04 10:09 UTC, guerler commented
Makes sense. Just wanted to make sure that testing both invocation orders is really the right thing to do. Thx.

2016-10-04 15:07 UTC, martenson commented
I tried to do some black box testing here and when I try to run it on this branch it instantly kills my browser tab.

![screenshot 2016-10-04 11 05 52](https://cloud.githubusercontent.com/assets/1814954/19079740/a0766ae4-8a22-11e6-8d7e-2c40fac2b346.png)

![screenshot 2016-10-04 11 06 12](https://cloud.githubusercontent.com/assets/1814954/19079746/a854558c-8a22-11e6-8d65-ed276ff5f8f9.png)

![screenshot 2016-10-04 11 05 28](https://cloud.githubusercontent.com/assets/1814954/19079754/ad45bb12-8a22-11e6-86ef-72148a727b97.png)

2016-10-04 16:31 UTC, martenson commented
update: Chrome with open devtools causes the issue above, with devtools closed it runs fine

howeverAnother issue is that if you open the run workflow in incognito window it will fail to render properly

![screenshot 2016-10-04 12 23 29](https://cloud.githubusercontent.com/assets/1814954/19083005/6cca4a9c-8a2e-11e6-8298-457b0e2e2de1.png)

2016-10-04 16:45 UTC, guerler commented
Very good catch. Hiding the child forms instead of removing them fixes the crash when Chromes devtools are open. I could not reproduce the second issue yet.

2016-10-04 16:50 UTC, martenson commented
I can produce the incognito issue reliably on a WF that has only the 'merge columns' tool in it.

2016-10-04 16:54 UTC, martenson commented
as a sideeffect of 329ee052510c0c720ae5d44bac23becf639f6506 the submission is _way_ faster

2016-10-04 17:02 UTC, martenson commented
the second issue was caused by a broken WF, when exported it has no steps:

```json
{
    "a_galaxy_workflow": "true", 
    "annotation": "", 
    "format-version": "0.1", 
    "name": "merge test", 
    "steps": {}, 
    "uuid": "87df19a4-454d-445b-ba2b-0f35676e14a0"
}
```

I think we should make WF creation atomic operation, but that is not the scope of this PR.

2016-10-04 19:23 UTC, martenson approved these changes
Looks and works very fine to me. Thank you duo of  @guerler & @jmchilton

2016-10-04 19:50 UTC, jmchilton commented
Against dev:

```
BIOBLEND_GALAXY_API_KEY=a7bf49fe4fd4041a2a93de4d0901716b BIOBLEND_GALAXY_URL=http://localhost:8080/ nosetests tests/TestGalaxyWorkflows.py
test_cancelling_workflow_scheduling (tests.TestGalaxyWorkflows.TestGalaxyWorkflows) ... ok
test_export_workflow_to_local_path (tests.TestGalaxyWorkflows.TestGalaxyWorkflows) ... ok
test_get_workflows (tests.TestGalaxyWorkflows.TestGalaxyWorkflows) ... ok
test_import_workflow_from_local_path (tests.TestGalaxyWorkflows.TestGalaxyWorkflows) ... ok
test_run_workflow (tests.TestGalaxyWorkflows.TestGalaxyWorkflows) ... ok
test_show_workflow (tests.TestGalaxyWorkflows.TestGalaxyWorkflows) ... ok
test_workflow_scheduling (tests.TestGalaxyWorkflows.TestGalaxyWorkflows) ... ok

----------------------------------------------------------------------
Ran 7 tests in 15.312s

OK
```

Against this branch:

```
BIOBLEND_GALAXY_API_KEY=a7bf49fe4fd4041a2a93de4d0901716b BIOBLEND_GALAXY_URL=http://localhost:8080/ nosetests tests/TestGalaxyWorkflows.py
test_cancelling_workflow_scheduling (tests.TestGalaxyWorkflows.TestGalaxyWorkflows) ... ok
test_export_workflow_to_local_path (tests.TestGalaxyWorkflows.TestGalaxyWorkflows) ... ok
test_get_workflows (tests.TestGalaxyWorkflows.TestGalaxyWorkflows) ... ok
test_import_workflow_from_local_path (tests.TestGalaxyWorkflows.TestGalaxyWorkflows) ... ok
test_run_workflow (tests.TestGalaxyWorkflows.TestGalaxyWorkflows) ... ok
test_show_workflow (tests.TestGalaxyWorkflows.TestGalaxyWorkflows) ... ok
test_workflow_scheduling (tests.TestGalaxyWorkflows.TestGalaxyWorkflows) ... FAIL

======================================================================
FAIL: test_workflow_scheduling (tests.TestGalaxyWorkflows.TestGalaxyWorkflows)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/john/workspace/bioblend/tests/test_util.py", line 54, in wrapped_method
    return method(has_gi, *args, **kwargs)
  File "/home/john/workspace/bioblend/tests/test_util.py", line 54, in wrapped_method
    return method(has_gi, *args, **kwargs)
  File "/home/john/workspace/bioblend/tests/TestGalaxyWorkflows.py", line 54, in test_workflow_scheduling
    self.assertEqual(invocation['state'], "ready")
AssertionError: u'new' != 'ready'
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/tools?in_panel=False&key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/tools?in_panel=False&key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /api/workflows/upload?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /api/histories?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /api/tools?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/workflows/59c76a119581e190/invocations?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "POST /api/workflows/59c76a119581e190/invocations?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/workflows/59c76a119581e190/invocations?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/workflows/59c76a119581e190/invocations/e89067bb68bee7a0?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/workflows/59c76a119581e190/invocations/e89067bb68bee7a0?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/workflows/59c76a119581e190/invocations/e89067bb68bee7a0?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/workflows/59c76a119581e190/invocations/e89067bb68bee7a0?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/workflows/59c76a119581e190/invocations/e89067bb68bee7a0?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/workflows/59c76a119581e190/invocations/e89067bb68bee7a0?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/workflows/59c76a119581e190/invocations/e89067bb68bee7a0?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/workflows/59c76a119581e190/invocations/e89067bb68bee7a0?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/workflows/59c76a119581e190/invocations/e89067bb68bee7a0?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/workflows/59c76a119581e190/invocations/e89067bb68bee7a0?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/workflows/59c76a119581e190/invocations/e89067bb68bee7a0?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/workflows/59c76a119581e190/invocations/e89067bb68bee7a0?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/workflows/59c76a119581e190/invocations/e89067bb68bee7a0?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/workflows/59c76a119581e190/invocations/e89067bb68bee7a0?key=a7bf49fe4fd4041a2a93de4d0901716b HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.url [...]

2016-10-04 20:03 UTC, jmchilton commented
Appears to be something up with the history id being empty on the resulting invocation.

2016-10-05 12:47 UTC, merged