Add documentation on optional ``multiple="true"`` data parameters.
galaxyproject/galaxy pull request #3024
Opened 2016-10-07 19:58 UTC by jmchilton

Thanks to detailed biostar question from @lindenb (sorry these parameters are so counter-intuitive - I don't have an excuse other than a need to preserve backward compatibility).

2016-10-07 23:38 UTC, erasche commented
> No line of output file was 'This is a line of text.' (output was '') 

Otherwise, nice to have that idiom documented! :)

2016-10-10 11:08 UTC, nsoranzo requested changes

2016-10-10 11:08 UTC, nsoranzo commented on lib/galaxy/tools/xsd/galaxy.xsd
> +effectively a list with one ``None``-like entity in it.
s/effectively a list/effectively be a list/

2016-10-10 11:08 UTC, nsoranzo commented on lib/galaxy/tools/xsd/galaxy.xsd
> +#end if
Indentation would be nice.

2016-10-10 11:08 UTC, nsoranzo commented on lib/galaxy/tools/xsd/galaxy.xsd
> +```
The test tool is failing, not sure this syntax is the problem, but I know of another way to process `$input1`:
```
#if str($input1) != 'None'
    #for $input in $input1
        -B "$input"
    #end for
#end if
```
See e.g. https://github.com/galaxyproject/tools-iuc/blob/master/tools/abyss/abyss-pe.xml#L111
I think that ```#if len($input1) != 0``` may be also used as initial test, see https://github.com/galaxyproject/tools-iuc/blob/master/tools/tool_factory_2/rgToolFactory2.xml#L47

2016-10-10 14:48 UTC, jmchilton commented on lib/galaxy/tools/xsd/galaxy.xsd
> +```
```
#if str($input1) != 'None'
```

should be strongly be considered an anti-pattern in my opinion. It isn't the least bit intuitive or Pythonic and it is really tied down to the internals of Galaxy and these wrappers. It also assumes more from the templating language which makes the tool more tied to Cheetah and Galaxy. Templating elements should be as light-weight as possible to make the tool work.

The length thing doesn't work in hands:

```
cat: None: No such file or directory
```

Galaxy really is creating a list with a None-like thing in it - I think the length is 1 unfortunately.

2016-10-10 14:51 UTC, jmchilton commented on lib/galaxy/tools/xsd/galaxy.xsd
> +#end if
I've rebased with this indentation. I feel like I see a lot of IUC tools without indentation though - we should codify this in the IUC best practices document on way or the other (I don't see anything in there currently but maybe I missed it).

2016-10-10 14:52 UTC, jmchilton commented on lib/galaxy/tools/xsd/galaxy.xsd
> +effectively a list with one ``None``-like entity in it.
I've made this change, thanks for the catch.

2016-10-10 15:24 UTC, nsoranzo commented on lib/galaxy/tools/xsd/galaxy.xsd
> +#end if
I am pretty sure all or most tools in `tools-iuc` have indentation in `<command>`, but you are right that this is not specified in the best practices. I'll open a PR.

2016-10-10 18:54 UTC, nsoranzo commented
@galaxybot test this

2016-10-11 09:59 UTC, nsoranzo commented on lib/galaxy/tools/xsd/galaxy.xsd
> +```
Then I guess that `tool_factory_2` tool is broken. Agreed that the `str($input1) != 'None'` syntax is not ideal, but is useful if you don't want to test every element of the list. I suppose adding a test using it would be good, just to make sure this does not break with future (and needed) refactoring of this code.

2016-10-11 09:59 UTC, nsoranzo approved these changes

2016-10-13 00:05 UTC, merged