Escape section name when writing to xml,
galaxyproject/galaxy pull request #3122
Opened 2016-11-03 16:15 UTC by mvdbeek

unescape when building ToolSection.
Should hopefully fix #3084 and the problem Miuki reported on the Mailing List.

This allows to have "beautiful" section like that:
![screenshot from 2016-11-03 16-57-31](https://cloud.githubusercontent.com/assets/6804901/19974279/34782cfa-a1e8-11e6-8817-7e356a44354c.png)

Ping @peterjc @nsoranzo

2016-11-03 16:58 UTC, nsoranzo requested changes

2016-11-03 16:58 UTC, nsoranzo commented on lib/tool_shed/galaxy_install/tools/tool_panel_manager.py
> +            section_id = escape(str( new_tool_panel_section_label.lower()).replace( ' ', '_' ) )
You are escaping `new_tool_panel_section_label` twice, you can remove `escape()` from this line.

2016-11-03 19:06 UTC, nsoranzo commented
It seems to me that only the modifications to `lib/galaxy/tools/toolbox/integrated_panel.py` (where the XML is written "manually") are needed, loading from XML is performed by `galaxy.util.parse_xml` which already performs the necessary unescaping.

@mvdbeek Are you sure the modifications to the other 2 files are needed?

2016-11-04 09:30 UTC, mvdbeek commented
You're right, this works fine.

2016-11-04 10:18 UTC, nsoranzo approved these changes

2016-11-04 10:29 UTC, mvdbeek commented
I'll just rebase this, no need for this to be 3 commits.

2016-11-04 11:16 UTC, merged

2016-11-04 11:16 UTC, nsoranzo commented
Thanks @mvdbeek!

2016-11-04 11:28 UTC, mvdbeek commented
Thanks for the review, I always appreciate it!