extend API version information
galaxyproject/galaxy pull request #3411
Opened 2017-01-12 12:19 UTC by manabuishii

extend API version information #1907
https://github.com/galaxyproject/galaxy/issues/1907

extend /api/version

output json file contents with version_major

```
{"extra": {"user_tag": "_fix_job_runner_issue", "commit-id": "abcde123"}, "version_major": "16.10"}
```

First check environment value GALAXY_VERSION_JSON_FILE.
if it's not set, try "galaxy root direcotory"/version.json.

if json file is not find, extra set empty.

2017-01-12 14:40 UTC, martenson commented
@galaxybot test this

2017-01-12 14:41 UTC, martenson commented
@manabuishii thanks for the PR, please fix the linting errors reported by Travis.

2017-01-13 13:37 UTC, martenson commented
@galaxybot test this

2017-01-13 14:26 UTC, martenson commented
@galaxybot test this

2017-01-13 14:50 UTC, jmchilton requested changes
Thanks for the contribution @manabuishii. Can you cherry-pick https://github.com/jmchilton/galaxy/commit/d744f797bf24e7cc57db42342f19c9ee3d2ed494 into your branch - it cleans up the Python some more.

```
git remote add jmchilton git@github.com:jmchilton/galaxy.git
git fetch jmchilton
git chery-pick d744f797bf24e7cc57db42342f19c9ee3d2ed494
```

2017-01-16 15:56 UTC, martenson commented
@galaxybot test this

2017-01-18 17:02 UTC, jmchilton approved these changes

2017-01-18 17:03 UTC, merged