Synnefo/Pithos+ object store backend
galaxyproject/galaxy pull request #3611
Opened 2017-02-14 15:12 UTC by saxtouri

An implementation of the storage backend class (lib/galaxy/objectstore: ObjectStore)  for Synnefo/Pithos+ object store ( https://www.synnefo.org/docs/synnefo/latest/pithos.html ) for Galaxy.

The implementation is using "kamaki", which is the Synnefo API client ( https://www.synnefo.org/docs/kamaki/latest/ ).

2017-02-15 13:51 UTC, saxtouri commented
The tests do not fail on my system. It seems that the tests fail on travis on the "import kamaki" line, but I have added "kamaki" to "conditional-requirements.txt" and this seems to suffice on my tests.

Any suggestions on what went wrong?

2017-02-16 21:31 UTC, bgruening commented
@saxtouri I guess Galaxy needs a wheel to make this work. Can you create one with starforge? https://github.com/galaxyproject/starforge/blob/master/wheels/build/wheels.yml

2017-02-20 17:40 UTC, martenson commented
The wheels for Kamaki are now available: https://depot.galaxyproject.org/starforge/wheels/build-165/

2017-02-20 18:13 UTC, martenson commented on lib/galaxy/dependencies/conditional-requirements.txt
> +kamaki
this also needs something like this:
```
def check_kamaki( self ):
        return 'pithos' in self.object_stores
```

around [here](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/dependencies/__init__.py#L108)

2017-02-20 18:13 UTC, martenson requested changes
please see above

2017-02-21 14:25 UTC, saxtouri commented on lib/galaxy/dependencies/conditional-requirements.txt
> +kamaki
Done! Thanks!

2017-02-21 16:06 UTC, martenson commented
The failing test is due to our (lack of) architecture for testing conditional dependencies. I am trying to work it out.

2017-03-04 02:44 UTC, martenson commented
@galaxybot test this

2017-03-14 13:16 UTC, saxtouri commented
@galaxybot test this

2017-03-14 14:09 UTC, nsoranzo commented
@galaxybot test this

2017-03-14 14:44 UTC, martenson approved these changes

2017-03-14 14:45 UTC, martenson commented
From my standpoint LGTM. However someone more fluent in object store should have a look here before this gets merged.

2017-04-13 20:18 UTC, bgruening commented
@dannon @natefoo would be great to get your input here :)
@saxtouri thanks, great work!

2017-05-01 13:54 UTC, dannon commented
@saxtouri This looks great to me, but prior to incorporation, would you mind dropping the copyright statement?  It'd be fine to change it to an attribution statement/comment if you'd like (so, something like "This work originally developed by <people> at <institution>"), and add yourself to https://github.com/galaxyproject/galaxy/blob/dev/CONTRIBUTORS.md, but code contributions should fall under the general project copyright and licensing terms.

2017-07-05 20:16 UTC, jmchilton commented
Ping @saxtouri again - is that copyright request reasonable?

2017-07-06 07:34 UTC, saxtouri commented
Sorry for the delay, of course it is reasonable, I'm updating this today.

2017-07-11 11:21 UTC, saxtouri commented
OK, I removed the copyright statement. I apologize for the delay. GRNET didn't really have a problem with this, the statement was put there by scripts I use.

2017-07-11 14:53 UTC, dannon commented
Thank you @saxtouri!  I'll run some final tests and merge this in a second.

2017-07-11 15:18 UTC, merged

2017-07-12 13:38 UTC, martenson commented
Thanks @saxtouri , very nice contribution!