Wiki to hub
galaxyproject/galaxy pull request #3754
Opened 2017-03-14 18:05 UTC by dannon

Unfortunately there are quite a few of these.  I updated a couple and pretty much immediately ran into a missing page, so I'm going to add those as I hit them.

This may be WIP for a while.

2017-03-14 18:34 UTC, nsoranzo commented
`doc/source/` also has a bunch of them.

2017-03-14 18:35 UTC, dannon commented
Yep, there are quite a few.  I'm grepping through incrementally.

2017-03-15 00:22 UTC, martenson commented
Redirects are in place so I believe we do not need to commit to a big cleanup.

2017-03-15 00:34 UTC, dannon commented
I agree to the extent that because of the redirects it's not particularly important to get this out the door right away, but we should still update URLs where they are incorrect, and I'll do so in this PR.

2017-04-26 16:09 UTC, nsoranzo commented
@dannon If you fix the merge conflict and remove the WIP label, I'll review and eventually merge this.

2017-04-26 16:11 UTC, dannon commented
@nsoranzo Yep.  Going to make one quick pass over it when we're off the call and will take it out of WIP today.

2017-04-26 21:19 UTC, dannon commented
(back in WIP for a sec -- merge looks like it had an issue)

2017-04-26 22:14 UTC, nsoranzo commented
I suppose the qunit build failure is legit?

2017-04-26 22:25 UTC, dannon commented
@nsoranzo Yep, could be, I'll look at it.

2017-04-26 22:31 UTC, dannon commented
Yep, just need to update a test case, one sec.

2017-04-26 23:46 UTC, nsoranzo commented
Thanks, I thought that was the case. Let's do the other tests too when Jenkins is back.

2017-04-27 18:32 UTC, jmchilton commented
@galaxybot test this

2017-04-28 11:40 UTC, nsoranzo requested changes

2017-04-28 11:40 UTC, nsoranzo commented on CITATION
> +See also: http://galaxyproject.org/citing-galaxy
https

2017-04-28 11:40 UTC, nsoranzo commented on client/galaxy/scripts/mvc/library/library-folderlist-view.js
> +          ' please consult the <a href="https://galaxyproject.org/admin/data-libraries/library-security" target="_blank">library security wikipage</a>',
https://galaxyproject.org/data-libraries/#permissions

2017-04-28 11:40 UTC, nsoranzo commented on client/galaxy/scripts/mvc/workflow/workflow-forms.js
> +                    help        : 'This action will rename the output dataset. Click <a href="https://galaxyproject.org/learn/advanced-workflow/variables-edit/">here</a> for more information. Valid i
https://galaxyproject.org/learn/advanced-workflow/variables/

2017-04-28 11:40 UTC, nsoranzo commented on config/galaxy.ini.sample
> +#search_url = http://galaxyproject.org/search/
https

2017-04-28 11:40 UTC, nsoranzo commented on config/galaxy.ini.sample
> +# https://galaxyproject.org/admin/data-libraries/uploading-library-files
https://galaxyproject.org/data-libraries/

2017-04-28 11:40 UTC, nsoranzo commented on config/galaxy.ini.sample
> +#   https://galaxyproject.org/admin/interface
https://galaxyproject.org/admin/

P.S.: https://wiki.galaxyproject.org/Admin/Interface is missing a proper redirect.

2017-04-28 11:40 UTC, nsoranzo commented on templates/webapps/galaxy/galaxy.masthead.mako
>              'search_url'                : app.config.get("search_url", "http://galaxyproject.org/search/usegalaxy/"),
https://galaxyproject.org/search/

2017-04-28 11:40 UTC, nsoranzo commented on templates/webapps/tool_shed/base_panels.mako
>                          [_('Search'), app.config.get( "search_url", "http://galaxyproject.org/search/usegalaxy/" ), "_blank" ],
https://galaxyproject.org/search/

2017-04-28 11:40 UTC, nsoranzo commented on lib/galaxy/webapps/galaxy/api/tool_shed_repositories.py
>      message += 'Installing_Galaxy_tool_shed_repository_tools_into_a_local_Galaxy_instance.'
The full link was continuing on the next line, so the proper link now is: https://galaxyproject.org/installing-repositories-to-galaxy/#installing-galaxy-tool-shed-repository-data-types-into-a-local-galaxy-instance

P.S.: http://wiki.galaxyproject.org/InstallingRepositoriesToGalaxy is missing a proper redirect.

2017-04-28 11:40 UTC, nsoranzo commented on templates/admin/tool_shed_repository/select_tool_panel_section.mako
> +        If you discover a repository that causes problems after installation, contact <a href="https://wiki.galaxyproject.org/support" target="_blank">Galaxy support</a>,
https://galaxyproject.org/support/

2017-04-28 11:40 UTC, nsoranzo commented on templates/webapps/galaxy/admin/center.mako
> +                    Please see the <a href="https://galaxyproject.org/admin/data-libraries/library-sample-tracking" target="_blank">sample tracking tutorial</a>.
https://galaxyproject.org/archive/library-sample-tracking/

P.S.: https://wiki.galaxyproject.org/Admin/DataLibraries/LibrarySampleTracking is missing a proper redirect.

2017-04-28 11:40 UTC, nsoranzo commented on templates/webapps/tool_shed/base_panels.mako
> +                        [_('Tool Shed Wiki'), app.config.get( "wiki_url", "https://galaxyproject.org/tool-shed" ), "_blank" ],
https://galaxyproject.org/toolshed/

2017-04-28 13:37 UTC, dannon commented on lib/galaxy/webapps/galaxy/api/tool_shed_repositories.py
>      message += 'Installing_Galaxy_tool_shed_repository_tools_into_a_local_Galaxy_instance.'
@nsoranzo This one's not quite right -- given the context it looks like it should just link to the base page.

2017-04-28 13:37 UTC, dannon commented on templates/admin/tool_shed_repository/select_tool_panel_section.mako
> +        If you discover a repository that causes problems after installation, contact <a href="https://wiki.galaxyproject.org/support" target="_blank">Galaxy support</a>,
@nsoranzo What's wrong with this one?

2017-04-28 13:45 UTC, dannon commented on templates/admin/tool_shed_repository/select_tool_panel_section.mako
> +        If you discover a repository that causes problems after installation, contact <a href="https://wiki.galaxyproject.org/support" target="_blank">Galaxy support</a>,
Argh, nevermind :)

2017-04-28 13:47 UTC, dannon commented on config/galaxy.ini.sample
> +#   https://galaxyproject.org/admin/interface
https://github.com/galaxyproject/infrastructure-playbook/commit/32d21f9efdbd2ca03532d0fa38184fde4db21d89

2017-04-28 13:51 UTC, dannon commented on templates/webapps/galaxy/admin/center.mako
> +                    Please see the <a href="https://galaxyproject.org/admin/data-libraries/library-sample-tracking" target="_blank">sample tracking tutorial</a>.
https://github.com/galaxyproject/infrastructure-playbook/commit/97fe8f28d0e9f91fd422db185706d1e39214c9e4

2017-04-28 13:52 UTC, dannon commented on lib/galaxy/webapps/galaxy/api/tool_shed_repositories.py
>      message += 'Installing_Galaxy_tool_shed_repository_tools_into_a_local_Galaxy_instance.'
https://github.com/galaxyproject/infrastructure-playbook/commit/97fe8f28d0e9f91fd422db185706d1e39214c9e4

2017-04-28 14:29 UTC, nsoranzo commented on lib/galaxy/webapps/galaxy/api/tool_shed_repositories.py
>      message += 'Installing_Galaxy_tool_shed_repository_tools_into_a_local_Galaxy_instance.'
> @nsoranzo This one's not quite right -- given the context it looks like it should just link to the base page.

Agreed.

2017-04-28 14:43 UTC, nsoranzo approved these changes
Thanks @dannon for bearing with me, there are still 2 small partially-fixed tweaks, I'll fix them, resolve the merge conflicts locally and merge.

2017-04-28 14:43 UTC, nsoranzo commented on client/galaxy/scripts/mvc/library/library-folderlist-view.js
> +          ' please consult the <a href="https://galaxyproject.org/admin/data-libraries/#permissions" target="_blank">library security wikipage</a>',
https://galaxyproject.org/data-libraries/#permissions

2017-04-28 14:43 UTC, nsoranzo commented on config/galaxy.ini.sample
> +# https://galaxyproject.org/admin/data-libraries/
https://galaxyproject.org/data-libraries/

2017-04-28 14:49 UTC, dannon commented
@nsoranzo Sounds good, thanks!  Always feel free to just PR against my branches or whatever, too, if that's easier.

2017-04-28 15:39 UTC, merged