Allow explicit configuration of handlers for workflow scheduling.
galaxyproject/galaxy pull request #3844
Opened 2017-03-29 20:20 UTC by jmchilton

Currently every job handler is a workflow scheduler handler and vice versa. This (in particular bb1bb67) allow specifying a separate (or potentially overlapping) pool of workflow schedulers. Includes lots of testing for figuring out if the current process is a workflow handler and for determining what handler should be assigned for queued workflows.

Builds on the testing from #3820 so it includes that PR and a merge forward of everything into dev.

A long discussion of how this may potentially improve performance, robustness, and quality of logs for workflow scheduling can be found as part of https://github.com/galaxyproject/galaxy/issues/3816#issuecomment-289323288.

2017-04-07 16:27 UTC, jmchilton commented
Ping @natefoo 🙏

2017-04-07 17:37 UTC, nsoranzo commented
:+1: to the use of _single_leading_underscore for internal methods.

2017-04-07 19:41 UTC, nsoranzo requested changes
I guess this needs a sample config file and/or some admin documentation?

2017-04-07 19:41 UTC, nsoranzo commented on lib/galaxy/util/handlers.py
> +                id = handler.get('id')
I'll put here my usual complain about the reserved word `id` used as a variable name ;)

2017-04-07 19:41 UTC, nsoranzo commented on lib/galaxy/jobs/__init__.py
> +            if id not in self.handler_runner_plugins:
`id` (again bad variable name...) is not defined in this method, should be passed as parameter!

2017-04-07 19:41 UTC, nsoranzo commented on lib/galaxy/util/handlers.py
> +    def _get_default(self, app, parent, names):
You may want to pass `config` instead of `app` here, since that's the only part that's used, but not a showstopper.

2017-04-07 20:15 UTC, jmchilton commented on lib/galaxy/util/handlers.py
> +                id = handler.get('id')
This code was refactored out of jobs/__init__.py that had the same problem but I'll definitely change it - good catch.

2017-04-07 20:19 UTC, jmchilton commented
> I guess this needs a sample config file and/or some admin documentation?

I was hoping to follow this up quickly with a switch to YAML - I don't want to write or encourage others to edit more XML.

If you insist on documentation, I'm going to rework the configuration files and add it to this PR - but this PR will be less focused as a result.

2017-04-07 20:21 UTC, jmchilton commented on lib/galaxy/util/handlers.py
> +    def _get_default(self, app, parent, names):
I like that change for sure - I'll make it.

2017-04-07 20:24 UTC, jmchilton commented on lib/galaxy/jobs/__init__.py
> +            if id not in self.handler_runner_plugins:
😱 So we would seem to have no test coverage in any of our tests for that. Thanks for the catch 🦅👀!

2017-04-07 21:47 UTC, nsoranzo approved these changes

2017-04-08 12:06 UTC, bgruening commented
Nice idea! Looking forward to use this. Would be great if you can add some docs in a follow up PR to also use different hosts for wf-scheduling.

2017-04-13 20:14 UTC, merged