Touch up #3559 based on post-merge discussions.
galaxyproject/galaxy pull request #3857
Opened 2017-03-31 20:17 UTC by jmchilton

xref #3559

2017-04-03 10:06 UTC, nsoranzo requested changes
`:returns:` and `:rtype:` of the 2 methods' documentation need to be updated accordingly.

2017-04-03 10:06 UTC, nsoranzo commented on lib/galaxy/webapps/galaxy/api/folder_contents.py
> +                return rvals
You can remove `rvals` and just do:
```python
                 return self._copy_hdca_to_library_folder( trans, self.hda_manager, decoded_hdca_id, encoded_folder_id_16, ldda_message )
```

2017-04-03 16:29 UTC, jmchilton commented
@nsoranzo I think I rebased this to address your concerns - let me know if this is not the case.

2017-04-03 16:33 UTC, nsoranzo commented on lib/galaxy/webapps/galaxy/api/folder_contents.py
> +                    of dictionaries describing the new items if ``from_hdca_id`` is supplied.
Double `of` ;)

2017-04-03 16:33 UTC, nsoranzo commented on lib/galaxy/webapps/galaxy/api/folder_contents.py
> +                return self._copy_hdca_to_library_folder( trans, self.hda_manager, decoded_hdca_id, encoded_folder_id_16, ldda_message ))
There's an extra `)` at the end here.

2017-04-04 11:54 UTC, nsoranzo approved these changes

2017-04-04 11:54 UTC, nsoranzo commented
@mvdbeek Merge?

2017-04-04 12:00 UTC, mvdbeek approved these changes
Yes, that looks better. Thanks @jmchilton and @nsoranzo !

2017-04-04 12:00 UTC, merged

2017-04-04 13:07 UTC, nsoranzo commented
Thanks, BioBlend is fixed on `dev` now!