Use the configured tool_path when loading data managers
galaxyproject/galaxy pull request #3989
Opened 2017-04-27 19:58 UTC by davebx

This should address #3606

2017-04-27 20:39 UTC, martenson commented on lib/tool_shed/galaxy_install/tools/data_manager.py
> +# <data_managers tool_path="/var/galaxy/data_managers">
this is probably a dev remnant?

2017-04-27 20:45 UTC, davebx commented on lib/tool_shed/galaxy_install/tools/data_manager.py
> +# <data_managers tool_path="/var/galaxy/data_managers">
That is exactly what it is. I even reminded myself to remove it before pushing.

2017-04-27 23:19 UTC, nsoranzo requested changes

2017-04-27 23:19 UTC, nsoranzo commented on lib/tool_shed/galaxy_install/tools/data_manager.py
> +
Can you remove one blank line to make flake8 happy?

2017-04-27 23:19 UTC, nsoranzo commented on lib/tool_shed/galaxy_install/tools/data_manager.py
> +        return data_managers_path
`data_managers_path` is undefined if bool(tree) is False

2017-04-27 23:19 UTC, nsoranzo commented on lib/galaxy/tools/data_manager/manager.py
> +            self.load_manager_from_elem( data_manager_elem, tool_path=tool_path, replace_existing=replace_existing )
This should be `tool_path=self.tool_path` because `tool_path` is undefined if `store_tool_path` is False.

2017-04-28 14:24 UTC, nsoranzo commented on lib/tool_shed/galaxy_install/tools/data_manager.py
> +            return root.get( 'tool_path', None )
Thanks @davebx! Maybe also add:
```python
        return None
```
for the case when `tree` is `None`.

2017-04-28 14:44 UTC, davebx commented on lib/tool_shed/galaxy_install/tools/data_manager.py
> +            return root.get( 'tool_path', None )
It was my understanding that if nothing specific is returned from a python function, the interpreter sets the return value to `None`, right?

2017-04-28 15:00 UTC, davebx commented on lib/tool_shed/galaxy_install/tools/data_manager.py
> +            return root.get( 'tool_path', None )
Then again, the Zen of Python, koan #2 states: Explicit is better than implicit.

2017-04-28 15:00 UTC, nsoranzo commented on lib/tool_shed/galaxy_install/tools/data_manager.py
> +            return root.get( 'tool_path', None )
You're right, didn't think of that, but I surely agree with the title of your last commit, explicit is indeed better than implicit!

2017-04-28 15:01 UTC, nsoranzo approved these changes

2017-04-28 17:44 UTC, davebx commented
That one API test seems to fail every now and then for reasons unrelated to the code, don't know what's going on there.

2017-04-28 17:48 UTC, mvdbeek commented
Right, this one is failing in other PRs as well.

2017-04-28 17:48 UTC, merged

2017-04-28 17:48 UTC, mvdbeek commented
We may want to target 17.01 as well, right?