Admin grid toolversion and quota grid with forms
galaxyproject/galaxy pull request #4411
Opened 2017-08-10 18:48 UTC by guerler

Removes grid and form makos used for the admin grid quota and tool version handling. Branched from #4405.

2017-08-15 19:19 UTC, martenson requested changes
when trying to create a quota I get this
```
DataError: (psycopg2.DataError) invalid input syntax for integer: "8ad7aaf8de1bd67f"
LINE 3: WHERE galaxy_user.id = '8ad7aaf8de1bd67f'
```

Also when creating quota please re-label the button to something other than `save settings` - e.g. `Create quota`.

2017-08-15 19:19 UTC, martenson commented on lib/galaxy/webapps/galaxy/controllers/admin.py
> +                            'label'   : 'Assign, increase by amount, or decrease by amount?',
this should probably read `Is this quota a default for a class of users (if yes, what type)?`

2017-08-16 18:18 UTC, martenson requested changes
when trying to search on the quota grid I get an alert with `Grid refresh failed` and this stacktrace:
<detail>
```
galaxy.web.framework.decorators ERROR 2017-08-16 14:17:24,596 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/Users/marten/devel/git/galaxy/lib/galaxy/web/framework/decorators.py", line 154, in decorator
    rval = func( self, trans, *args, **kwargs)
  File "/Users/marten/devel/git/galaxy/lib/galaxy/web/framework/decorators.py", line 98, in decorator
    return func( self, trans, *args, **kwargs )
  File "/Users/marten/devel/git/galaxy/lib/galaxy/webapps/galaxy/controllers/admin.py", line 574, in quotas_list
    return self.quota_list_grid( trans, **kwargs )
  File "/Users/marten/devel/git/galaxy/lib/galaxy/web/framework/helpers/grids.py", line 221, in __call__
    total_num_rows = query.count()
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2980, in count
    return self.from_self(col).scalar()
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2749, in scalar
    ret = self.one()
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2718, in one
    ret = list(self)
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/Users/marten/devel/git/galaxy/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'property' [SQL: 'SELECT count(*) AS count_1 \nFROM (SELECT quota.id AS quota_id, quota.create_time AS quota_create_time, quota.update_time AS quota_update_time, quota.name AS quota_name, quota.description AS quota_description, quota.bytes AS quota_bytes, quota.operation AS quota_operation, quota.deleted AS quota_deleted \nFROM quota \nWHERE lower(quota.name) LIKE %(lower_1)s OR lower(quota.description) LIKE %(lower_2)s OR lower(%(lower_3)s) LIKE %(lower_4)s ORDER BY lower(quota.name) ASC) AS anon_1'] [parameters: {'lower_1': u'%test%', 'lower_3': <property object at 0x106521d08>, 'lower_2': u'%test%', 'lower_4': u'%test%'}]
```
</detail>

2017-08-16 18:20 UTC, martenson commented
Also when switching between grids the search terms seem to stick. Also multiple same searchterms are allowed. 
![screenshot 2017-08-16 14 19 35](https://user-images.githubusercontent.com/1814954/29378693-01afc486-828e-11e7-896f-ed4f60df2473.png)

2017-08-16 18:21 UTC, martenson commented
So the grid search error is also happening on Main...

2017-08-16 18:49 UTC, guerler commented
"when switching between grids the search terms seem to stick" is an issue I am aware of and a related to how we handle url parameters i.e. passing them through the backend. It is something we can fix when working on the router again.

2017-08-16 19:16 UTC, martenson commented
When using the advanced search, after triggering, the advanced search switches to the normal search. The previous behavior was that it stayed in the advanced setting after delivering the results.

2017-08-16 19:19 UTC, martenson approved these changes

2017-08-16 19:19 UTC, merged

2017-08-16 19:19 UTC, martenson commented
So there are few items left after merging:

- When using the advanced search, after triggering, the advanced search switches to the normal search. The previous behavior was that it stayed in the advanced setting after delivering the results.
- When switching between grids the search terms seem to stick. 
- Multiple same searchterms are allowed.

2017-08-16 20:17 UTC, guerler commented
Thanks a lot for the detailed review.