Dynamic post-processing actions
galaxyproject/galaxy pull request #5439
Opened 2018-02-01 20:58 UTC by anatskiy

The PR adds a new feature by executing a custom Python function after a workflow run. In this example, Galaxy sends a simple desktop notification:

![screenshot from 2018-02-01 20-41-13](https://user-images.githubusercontent.com/7281783/35702786-529f01d6-079a-11e8-8f7e-5160592c72e5.png)

![screenshot from 2018-02-01 20-42-45](https://user-images.githubusercontent.com/7281783/35702877-9aa52cda-079a-11e8-9956-a585c9dda152.png)

All credits go to @bgruening, I just adapted the 3-year-old feature to the latest dev.

2018-02-05 18:26 UTC, bgruening commented
@dannon do you remember our discussion about this extension? 3 years ago we were able to control a robot depending on the output of a workflow, sample new data and resubmit a workflow. A feedback loop was with this possible :)

![](https://github.com/bgruening/hackathonfr/raw/master/presentation/eve_annot.png)

https://github.com/bgruening/hackathonfr

2018-02-05 18:38 UTC, martenson requested changes
please remove the `static/script` files and rebase, we no longer track these artifacts in git

2018-02-05 18:38 UTC, martenson commented on config/galaxy.yml.sample
>  # Galaxy is configured by default to be usable in a single-user development
this file is [generated](manage-script-name) from [schema](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/config_schema.yml).

2018-02-08 11:54 UTC, anatskiy commented
@martenson for some reason I'm unable to revert the two remaining static files. The error is:
```
❯ git checkout e591288cadf5af3acb0700f01cbac1188f07abb1 static/scripts/libs/bibtex.js           
error: pathspec 'static/scripts/libs/bibtex.js' did not match any file(s) known to git.
```

2018-02-08 22:57 UTC, martenson commented
@anatskiy I will have a look. You also need to generate the sample config (and commit it) using the makefile target I linked.

Thanks for the adjustments!

2018-02-11 20:37 UTC, anatskiy commented
@martenson what command generates a config file?

2018-02-11 21:11 UTC, martenson commented
@anatskiy `make config-rebuild` - sorry for including wrong link previously

2018-03-20 15:44 UTC, jmchilton commented
Clever with the docstring - I like that - looks good to me! I also like the client side piece is a light touch - this basically doesn't constrain frontend development at all. Thanks!

2018-03-20 16:07 UTC, martenson submitted a review, later dismissed

2018-03-20 16:15 UTC, jmchilton commented
Rerunning the qunit tests - those sometimes fail randomly but it looked like it might be related to the PR.

2018-03-20 16:15 UTC, jmchilton commented
@galaxybot test this

2018-03-20 16:35 UTC, guerler commented on client/galaxy/scripts/mvc/workflow/workflow-forms.js
> +    var dynamicActions = options.dynamicActions;
This is correct convention but in this file we are using underscores for variable names i.e. "dynamic_actions". Can you adjust this for consistency?

2018-03-20 16:36 UTC, guerler commented on lib/galaxy/jobs/actions/post.py
> +            print(class_object, module)
Debug output?

2018-03-20 16:46 UTC, guerler commented on lib/galaxy/webapps/galaxy/api/dynamic_actions.py
> +
Can you move the privilege check to `get_dynamic_post_processing_actions`?

2018-03-20 18:11 UTC, bgruening commented
Thanks all for the review. @RJMW any comments from your side?

2018-03-20 18:31 UTC, jmchilton commented
I think the qunit tests are failing because of changes in client/galaxy/scripts/mvc/workflow/workflow-forms.js. Sorry to pile on @anatskiy.

2023-02-16 18:34 UTC, closed without merging