WIP allows whitelisted symlinks to be imported from
galaxyproject/galaxy pull request #5596
Opened 2018-02-23 16:50 UTC by bwlang

needs testing, but I can't quickly find where the other methods in remote_files are tested...  
@natefoo can you comment on the implementation and you point me in the right direction on testing?

2018-02-23 17:08 UTC, natefoo requested changes
Thanks @bwlang! I think there is some duplication here, although I might be missing something.

2018-02-23 17:08 UTC, natefoo commented on lib/galaxy/util/path/__init__.py
> +def path_under_whitelist_dir(path, whitelist=None):
I think this duplicates `safe_contains()` below? You should be able to use `safe_contains(configured import root directory, path, whitelist)` I think.

2018-02-23 17:08 UTC, natefoo commented on lib/galaxy/webapps/galaxy/api/remote_files.py
>              for (dirpath, dirnames, filenames) in os.walk(directory):
I think the above would not be needed if this used `galaxy.util.path.unsafe_walk()` with the whitelist.

2018-02-23 20:31 UTC, bwlang commented
@natefoo 
I thought you'd want to allow symlinks pointing anywhere that's whitelisted, not just directories below the import root directory. Is that right?

where should the testing live for this code?

2018-02-26 17:44 UTC, natefoo commented
Ok, `safe_contains(directory, directory, whitelist)` does what you want, but feels a little clumsy, so your new function seems reasonable. I have a `safe_walk()` function I'd like to add, though. Do you mind if I PR against your branch?

2018-02-26 20:59 UTC, bwlang commented
Looking better after Nate's contribution... still not sure about testing this though.

2018-02-27 20:13 UTC, natefoo commented
I'm told by @martenson that this failing test is flaky.

2018-02-27 20:13 UTC, natefoo commented
@galaxybot test this

2018-03-02 17:51 UTC, bwlang commented
That's some chatty selenium output...
maybe this test is not robust... seems like a timeout error unrelated to this commit to my eye.
@natefoo  thoughts?
```
======================================================================
ERROR: test_build_paired_list_hide_original (selenium_tests.test_collection_builders.CollectionBuildersTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/galaxy/test/selenium_tests/framework.py", line 148, in func_wrapper
    return f(self, *args, **kwds)
  File "/galaxy/test/selenium_tests/test_collection_builders.py", line 79, in test_build_paired_list_hide_original
    self.history_panel_wait_for_hid_visible(2)
  File "/galaxy/test/galaxy_selenium/navigates_galaxy.py", line 267, in history_panel_wait_for_hid_visible
    self.wait(timeout).until(history_has_hid)
  File "/galaxy_venv/local/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message: 
```

2018-03-02 19:51 UTC, natefoo commented
Yeah I don't think we broke this - someone else should perhaps +1/merge this since I contributed to it.

2018-03-02 20:36 UTC, merged

2018-03-02 20:36 UTC, martenson commented
Thanks @bwlang, @natefoo !