Add a job destination param for overriding the Singularity image path
galaxyproject/galaxy pull request #6114
Opened 2018-05-10 16:44 UTC by natefoo

This allows us to use stuff in e.g. `/cvmfs/singularity.galaxyproject.org` without having to support the `/singularity/mulled` that is automatically appended when using the `container_image_cache_path` option in the global config.

2018-05-11 08:06 UTC, jmchilton requested changes
This property name should to make it clear it only applies to this one flavor of container resolver (mulled). If you hate the mulled name and want to call them biocontainers or grueningcontainers that is fine.

I'd also like it to default to using the global config, but if you want to call that outside the scope of this PR I will survive.

2018-05-11 12:45 UTC, natefoo commented
> This property name should to make it clear it only applies to this one flavor of container resolver (mulled). If you hate the mulled name and want to call them biocontainers or grueningcontainers that is fine.

I'm confused - does the name not make it clear it's for Singularity only? Is there a non-mulled Singularity resolver?

> I'd also like it to default to using the global config, but if you want to call that outside the scope of this PR I will survive.

Does it not?:

```python
cache_directory = destination_info.get("singularity_image_dir", self.cache_directory)
```

2018-05-11 13:23 UTC, jmchilton commented
> Is there a non-mulled Singularity resolver?

Yes, the ``ExplicitContainerResolver`` can be used with Singularity for instance. One can imagine any number of other ways to produce containers from requirements or tools. We haven't invested much effort in others because we like the best practice - but the Galaxy should provide support for the best practices not lock people into them. Saying singularity -> mulled is like saying requirement -> Conda. We shouldn't be locking people into that.

Since you know how to use the container resolvers conf file now and you wanted to set on up to disable auto-build - do you want to just make set this attribute via  ``<cached_mulled cache_dir="/path/to/blah" />`` tag - that is how this was intended to be used now that I'm thinking about it. It also makes it very clear what resolver is using this option. I think the container resolvers may be configurable on a per-job destination basis if it needs to be - but we wouldn't even need to do that right?

2018-05-11 13:29 UTC, jmchilton commented
Other cool things about using the tag:

- I think that file can just be YAML like the dependency resolvers conf, so don't let the XML scare you off.
- I think it should work to just set up two cached mulled instances - one on cvmfs so the centrally managed containers and one local for the things built from the local tool panel (either automatically or manually).

2018-05-11 15:46 UTC, natefoo commented
> Since you know how to use the container resolvers conf file now and you wanted to set on up to disable auto-build - do you want to just make set this attribute via `<cached_mulled cache_dir="/path/to/blah" />` tag - that is how this was intended to be used now that I'm thinking about it. It also makes it very clear what resolver is using this option. I think the container resolvers may be configurable on a per-job destination basis if it needs to be - but we wouldn't even need to do that right?

Yeah, I guess we could do this, but it still requires them to live in `<cache_dir>/singularity/mulled` right? Also, you could imagine scenarios where you'd need a different image path for different destinations.

2018-05-11 16:25 UTC, jmchilton commented
> it still requires them to live in <cache_dir>/singularity/mulled right?

I really don't think so - https://github.com/galaxyproject/galaxy/pull/6122

> you could imagine scenarios where you'd need a different image path for different destinations.

Of course and for sure, we have per-job destination dependency resolution for the same reason. And I'll write you per job destination container resolvers once you need this - I've reviewed the code and it isn't there yet but it was always my intention I believe.

Update: Fixed to point at correct PR.

2018-05-23 19:57 UTC, natefoo commented
Closing in favor of #6122, thanks John.

2018-05-23 19:57 UTC, closed without merging