Enable manual user activation
galaxyproject/galaxy pull request #9143
Opened 2019-12-18 22:25 UTC by ic4f

Re #3208
Assumptions: confirmation not needed; single user activation only.
Refactoring: move user activation into user manager; update user controller.
TODO: selenium test (ideally, I think).

2019-12-18 23:16 UTC, nsoranzo approved these changes

2019-12-19 00:10 UTC, ic4f commented
Afterthoughts. 
1. The activation button is displayed regardless of the value of `app.config.user_activation_on`. Rationale: option might have been on, then turned off, with account(s) still needing activation.
2. I did not add a "deactivate user" option because I think it's not necessary. If, however, it could be helpful, pls let me know. Same for activating multiple users.

2019-12-19 15:31 UTC, martenson commented
> Rationale: option might have been on, then turned off, with account(s) still needing activation.

If the activation is turned off, the flag is never checked -> I think the button should be hidden.


> I did not add a "deactivate user"

+1

2019-12-19 15:35 UTC, martenson commented
I don't see the second commit in the list or in the files diff. 😕

2019-12-19 15:44 UTC, ic4f commented
> I don't see the second commit in the list or in the files diff. 😕

What second commit?

2019-12-19 15:46 UTC, martenson commented
Oh that was just a reference, nevermind. 🤣

2019-12-19 16:13 UTC, ic4f commented
> If the activation is turned off, the flag is never checked -> I think the button should be hidden.

I was about to agree.. But then I thought about it; I don't think we should disable that button if the flag is not set. (1) If the feature is disabled, there will be no new accounts that are not activated - so the button will not be displayed for those. It will only be displayed for non-activate accounts, and non-active accounts can only be possible if the feature (a) is enabled, or (b) has been enabled previously. And in the latter, I think it's convenient to have a button to cleanup after unsetting the flag. And (2): the flag does not disable user *activation status* - it disables the *policy* that requires that users must confirm their email address, after which the system activates their account. User status exists regardless of that policy. The button is an admin override for that status. What do you think? (also, I'm not a galaxy admin, so I'm only guessing here)

2019-12-19 16:24 UTC, martenson commented
I followed your rationale but suspect you might be overthinking it. I don't see a benefit in displaying control elements for features that are explicitly turned off.

2019-12-19 16:34 UTC, ic4f commented
> I followed your rationale but suspect you might be overthinking it. I don't see a benefit in displaying control elements for features that are explicitly turned off.

I might be. OK, I'll figure out how to make that change.

2019-12-20 00:16 UTC, ic4f commented
I can't see a better way to do this. In general, passing the app object may be useful in other scenarios down the road: the app holds the config, and grid elements may need to behave differently based on config settings. @martenson ? @nsoranzo : this has changed considerably since your approval.

2019-12-20 01:24 UTC, dannon requested changes
I would not do this like this.

2019-12-20 01:24 UTC, dannon commented on lib/galaxy/managers/users.py
> +    def activate(self, trans, user):
We don't need trans in this function if you use `self.session()`

2019-12-20 01:27 UTC, dannon commented on lib/galaxy/webapps/galaxy/controllers/admin.py
> +                            condition=(lambda item, app: app.config.user_activation_on and not item.active),
I would suggest not adding the option in this list, swapping the lambda back to a single argument without `app`, and then just conditionally add the GridOperation when the grid is initialized, based on the config at hand.

2019-12-20 01:28 UTC, dannon commented
@ic4f Sorry, github wouldn't accept the review comment submission, and now it's attached all wonky.  Let me know if the suggestion isn't clear and I can get an example together

2019-12-20 01:37 UTC, ic4f commented
@dannon - no worries! I don't see the wonky :) thing, and your comments make sense. I wasn't at all sure adding the arg was the best/only possible way. Will change it. Thanks for reviewing!

2019-12-20 01:39 UTC, dannon commented
@ic4f Ok, cool, just let me know if I can help :)  And, thanks for working on the suggestions!

2019-12-20 02:48 UTC, ic4f commented
@dannon Updated. Thanks - now I see it's done that way for other operations too.

2019-12-20 02:49 UTC, dannon commented
@ic4f Much better, thank you.

2019-12-20 14:47 UTC, merged

2019-12-20 14:49 UTC, martenson commented
Thanks @ic4f !