[20.01] Add requirements to (almost) all converts, proflle and minor fixess
galaxyproject/galaxy pull request #9345
Opened 2020-02-09 15:47 UTC by mvdbeek

Skipped those converters that are in https://github.com/galaxyproject/galaxy/pull/9336 and those that currently still import stuff from Galaxy that we can't replace yet with a proper conda package.

2020-02-09 18:19 UTC, mvdbeek commented
The output data for the new tests is missing ... it turns out planemo will run all converter tests, even if testing an unrelated tool :(.

2020-02-10 07:42 UTC, mvdbeek commented
Hmm, so this is because planemo runs `run_tests.sh functional.test_toolbox`, which tests all loaded tools. Since Galaxy instances managed by planemo don't load any tools, testing the toolbox will only run the desired tool tests. Except now the converters have tests, so they will be run as well.

Given that this behavior seems like a shortcut it might be best to parse out tool ids and test cases before starting the test instance and then to select those tests.

2020-02-10 13:28 UTC, KevinJ123 requested changes
Pull request

2020-02-10 16:27 UTC, mvdbeek commented
damn, times out without revealing the errors :/

2020-02-10 16:32 UTC, mvdbeek commented
Bumped the timeout up to 120 minutes. I guess we don't need to run the converter tests with every PR, but I think it's good to run them until they pass at least once.

2020-02-13 16:33 UTC, mvdbeek commented
Alright, green (mostly)! This is ready for review.

2020-02-14 19:16 UTC, jmchilton commented on .github/workflows/converter_tests.yaml
> +      run: 'planemo test --galaxy_python_version ${{ matrix.python-version }} --galaxy_root .  lib/galaxy/datatypes/converters/*xml'
This is a really interesting new test, this is going to catch a lot of potential problems outside just converters!

2020-02-14 19:24 UTC, jmchilton commented
Amazing!

2020-02-14 19:24 UTC, merged