fix searchgui_archive set_meta
galaxyproject/galaxy pull request #9437
Opened 2020-02-25 15:08 UTC by bernt-matthias

probably with py3 reading a file from a zip file became binary. hence `startswith` and `split` fail. 

Q is if this is the best possible fix? 

- Maybe use binary-strings for `split` and `startswith`?
- Or is there something is galaxy.utils that could help?

2020-02-25 16:48 UTC, ic4f commented
I think this is the simplest solution, and it works for both Py2 and Py3. Given the subsequent string manipulation, text makes more sense than bytes. +1. Needs to be merged forward, I believe.

2020-02-25 16:51 UTC, jdavcs approved these changes
unit test failure is unrelated.

2020-02-25 22:13 UTC, nsoranzo commented on lib/galaxy/datatypes/binary.py
>                              for line in fh:
```suggestion
                            for line in io.TextIOWrapper(fh):
```

2020-02-25 22:13 UTC, nsoranzo commented on lib/galaxy/datatypes/binary.py
> +                                line = line.decode()
```suggestion
```

2020-02-26 09:24 UTC, bernt-matthias commented
Thanks @nsoranzo for the suggestion. Do you think that this also might be the preferred solution for https://github.com/galaxyproject/galaxy/issues/9251 .. instead of `unicodify`?

2020-02-26 09:44 UTC, nsoranzo commented
> Thanks @nsoranzo for the suggestion. Do you think that this also might be the preferred solution for #9251 .. instead of `unicodify`?

I think `unicodify()` is fine for that, since stdout and stderr are plain strings.

2020-02-26 09:45 UTC, nsoranzo approved these changes

2020-02-26 09:46 UTC, nsoranzo requested changes
Ah, you need to add an `import io` at the top.

2020-02-26 09:56 UTC, nsoranzo approved these changes

2020-02-26 15:07 UTC, merged